"""
Run the triangular arbitrage pipeline on the checked-in synthetic dataset.

SYNTHETIC DATA - NOT REAL MARKET DATA. data/synthetic_fx_rates.csv is
generated by generate_synthetic_data.py from the model's own random-walk
simulation, which draws a mispricing term by construction, so it is
expected to contain detectable, tradable-looking arbitrage opportunities.
That is the model working as designed, not a market finding - contrast
with run_historical.py, which runs the same pipeline on real data and
finds effectively none. See README "Known issues and limitations".

This mirrors run_historical.py, reusing the existing, unmodified pipeline
classes via ExchangeRateData.load_historical_data().

Usage:
    python generate_synthetic_data.py   # writes data/synthetic_fx_rates.csv
    python run_synthetic.py
"""

import matplotlib
matplotlib.use("Agg")

from triangular_arbitrage_implementation import ExchangeRateData
from parameter_estimation import ParameterEstimator
from arbitrage_detection import ArbitrageDetector
from visualization import ArbitrageVisualizer

DATA_PATH = "data/synthetic_fx_rates.csv"
TRANSACTION_COST = 0.0005  # 0.05% per leg, same default as main.py


def run_synthetic_arbitrage_analysis(data_path=DATA_PATH, transaction_cost=TRANSACTION_COST):
    print("SYNTHETIC DATA - NOT REAL MARKET DATA (see README).")
    print("Loading synthetic exchange rate data...")
    exchange_data = ExchangeRateData(data_source='synthetic', num_periods=5)
    exchange_data.load_historical_data(data_path)
    print(f"Loaded {len(exchange_data.rates_df)} rows: "
          f"{exchange_data.rates_df.index.min()} to {exchange_data.rates_df.index.max()}")

    print("\nEstimating statistical parameters...")
    estimator = ParameterEstimator(exchange_data)
    parameters = estimator.estimate_all_parameters()
    for name, value in parameters.items():
        print(f"  {name}: {value}")

    print("\nDetecting arbitrage opportunities...")
    detector = ArbitrageDetector(
        exchange_data,
        mispricing_simulator=None,
        transaction_costs=transaction_cost,
    )
    detector.detect_opportunities()
    detector.calculate_profits()
    detector.analyze_feasibility()
    results_df, feasibility_summary = detector.get_results()

    print("Arbitrage feasibility summary (synthetic data):")
    for key, value in feasibility_summary.items():
        print(f"  {key}: {value}")

    print("\nCreating visualizations...")
    visualizer = ArbitrageVisualizer(
        exchange_data,
        parameter_estimator=estimator,
        mispricing_simulator=None,
        arbitrage_detector=detector,
    )
    visualizer.create_comprehensive_report(output_file="synthetic_arbitrage_report.pdf")
    print("Wrote synthetic_arbitrage_report.pdf")

    return exchange_data, estimator, detector, visualizer


if __name__ == "__main__":
    run_synthetic_arbitrage_analysis()
